%%
x=0:pi/10:2*pi;
f=sin(x);
figure
plot(x,f,'ob')
%%
Red=newff(x,f,[10],{'tansig','purelin'},'trainlm');
Red.dividefcn=''
Red.trainParam.goal=0
Red=train(Red,x,f);
%%
F=sim(Red,x);
figure
plot(x,f,'ob',x,F,'*r')
%%
xval=pi/20:pi/10:2*pi;
fval=sin(xval);
Fval=sim(Red,xval);
plot(x,f,'ob',x,F,'*r',xval,fval,'og',xval,Fval,'*g')
